"""Constants for the Bayrol integration."""

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorStateClass,
)

DOMAIN = "bayrol"

BAYROL_ACCESS_TOKEN = "bayrol_access_token"
BAYROL_DEVICE_ID = "bayrol_device_id"
BAYROL_DEVICE_TYPE = "bayrol_device_type"
BAYROL_APP_LINK_CODE = "bayrol_app_link_code"

BAYROL_HOST = "www.bayrol-poolaccess.de"
BAYROL_PORT = 8083

# MQTT value to display text mapping for Automatic models
AUTOMATIC_MQTT_TO_TEXT_MAPPING = {
    # Production rate mappings
    "19.3": "0.25x",
    "19.4": "0.5x",
    "19.5": "0.75x",
    "19.6": "1.0x",
    "19.7": "1.25x",
    "19.8": "1.5x",
    "19.9": "2x",
    "19.10": "3x",
    "19.11": "5x",
    "19.12": "10x",
    "19.17": "Yes",
    "19.18": "No",
    "19.106": "Constant mode",
    "19.115": "Auto plus+",
    "19.195": "Auto (redox control)",
    "19.258": "filled",
    "19.259": "empty",
    # Filtration mode mappings
    "19.315": "Low",
    "19.316": "Med",
    "19.317": "High",
    "19.346": "Auto",
    "19.330": "Smart",
    "19.338": "Frost",
    "19.312": "Off",
    # Out Mode mappings
    "19.311": "Out - On",
    "19.100": "Out - Off",
    "19.345": "Out - Auto",
    # Cover state mappings
    "19.55": "OFF",
    "19.142": "Open",
    "19.143": "Closed",
}

# MQTT value to display text mapping for PM5 models
PM5_MQTT_TO_TEXT_MAPPING = {
    # Pump on/off — discovered via MQTT sniffer on PM5 Chlorine
    "7001": "Inactive",
    "7002": "Active",
    # Cl pump select options
    "7408": "On",
    "7407": "Off",
    "7427": "Auto",
    # Filter pump mode options
    "7389": "Eco",
    "7390": "Normal",
    "7391": "High",
    "7392": "Auto",
    "7393": "Off",
    # Canister / level status
    "7521": "Full",
    "7522": "Low",
    "7523": "Empty",
    # General status codes
    "7524": "Ok",
    "7525": "Info",
    "7526": "Warning",
    "7527": "Alarm",
}

# Reverse mapping for display text to MQTT values for Automatic devices
AUTOMATIC_TEXT_TO_MQTT_MAPPING = {
    v: k for k, v in AUTOMATIC_MQTT_TO_TEXT_MAPPING.items()
}

# Reverse mapping for display text to MQTT values for PM5 devices
PM5_TEXT_TO_MQTT_MAPPING = {v: k for k, v in PM5_MQTT_TO_TEXT_MAPPING.items()}

# Common sensor types for Automatic devices
SENSOR_TYPES_AUTOMATIC = {
    "4.2": {
        "name": "pH Target",
        "device_class": SensorDeviceClass.PH,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 10,
        "unit_of_measurement": None,
        "entity_type": "select",
        "options": [
            6.2,
            6.3,
            6.4,
            6.5,
            6.6,
            6.7,
            6.8,
            6.9,
            7.0,
            7.1,
            7.2,
            7.3,
            7.4,
            7.5,
            7.6,
            7.7,
            7.8,
            7.9,
            8.0,
            8.1,
            8.2,
        ],
    },
    "4.3": {
        "name": "pH Alert Max",
        "device_class": SensorDeviceClass.PH,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 10,
        "unit_of_measurement": None,
        "entity_type": "select",
        "options": [
            7.2,
            7.3,
            7.4,
            7.5,
            7.6,
            7.7,
            7.8,
            7.9,
            8.0,
            8.1,
            8.2,
            8.3,
            8.4,
            8.5,
            8.6,
            8.7,
        ],
    },
    "4.4": {
        "name": "pH Alert Min",
        "device_class": SensorDeviceClass.PH,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 10,
        "unit_of_measurement": None,
        "entity_type": "select",
        "options": [
            5.7,
            5.8,
            5.9,
            6.0,
            6.1,
            6.2,
            6.3,
            6.4,
            6.5,
            6.6,
            6.7,
            6.8,
            6.9,
            7.0,
            7.1,
            7.2,
        ],
    },
    "4.5": {
        "name": "pH Dosing Control Time Interval",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": "min",
        "entity_type": "sensor",
    },
    "4.7": {
        "name": "Minutes Counter / Reset every hour",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": "min",
        "entity_type": "sensor",
    },
    "4.26": {
        "name": "Redox Alert Max",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": "mV",
        "entity_type": "select",
        "options": [
            995,
            990,
            985,
            980,
            975,
            970,
            965,
            960,
            955,
            950,
            945,
            940,
            935,
            930,
            925,
            920,
            915,
            910,
            905,
            900,
            895,
            890,
            885,
            880,
            875,
            870,
            865,
            860,
            855,
            850,
            845,
            840,
            835,
            830,
            825,
            820,
            815,
            810,
            805,
            800,
            795,
            790,
            785,
            780,
            775,
            770,
            765,
            760,
            755,
            750,
            745,
            740,
            735,
            730,
            725,
            720,
            715,
            710,
            705,
            700,
            695,
            690,
            685,
            680,
            675,
            670,
            665,
            660,
            655,
            650,
            645,
            640,
            635,
            630,
            625,
            620,
            615,
            610,
            605,
            600,
            595,
            590,
            585,
            580,
            575,
            570,
            565,
            560,
            555,
            550,
            545,
            540,
            535,
            530,
            525,
            520,
            515,
            510,
            505,
            500,
        ],
    },
    "4.27": {
        "name": "Redox Alert Min",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": "mV",
        "entity_type": "select",
        "options": [
            850,
            845,
            840,
            835,
            830,
            825,
            820,
            815,
            810,
            805,
            800,
            795,
            790,
            785,
            780,
            775,
            770,
            765,
            760,
            755,
            750,
            745,
            740,
            735,
            730,
            725,
            720,
            715,
            710,
            705,
            700,
            695,
            690,
            685,
            680,
            675,
            670,
            665,
            660,
            655,
            650,
            645,
            640,
            635,
            630,
            625,
            620,
            615,
            610,
            605,
            600,
            595,
            590,
            585,
            580,
            575,
            570,
            565,
            560,
            555,
            550,
            545,
            540,
            535,
            530,
            525,
            520,
            515,
            510,
            505,
            500,
            495,
            490,
            485,
            480,
            475,
            470,
            465,
            460,
            455,
            450,
            445,
            440,
            435,
            430,
            425,
            420,
            415,
            410,
            405,
            400,
            395,
            390,
            385,
            380,
            375,
            370,
            365,
            360,
            355,
            350,
            345,
            340,
            335,
            330,
            325,
            320,
            315,
            310,
            305,
            300,
            295,
            290,
            285,
            280,
            275,
            270,
            265,
            260,
            255,
            250,
            245,
            240,
            235,
            230,
            225,
            220,
            215,
            210,
            205,
            200,
        ],
    },
    "4.28": {
        "name": "Redox Target",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": "mV",
        "entity_type": "select",
        "options": [
            950,
            945,
            940,
            935,
            930,
            925,
            920,
            915,
            910,
            905,
            900,
            895,
            890,
            885,
            880,
            875,
            870,
            865,
            860,
            855,
            850,
            845,
            840,
            835,
            830,
            825,
            820,
            815,
            810,
            805,
            800,
            795,
            790,
            785,
            780,
            775,
            770,
            765,
            760,
            755,
            750,
            745,
            740,
            735,
            730,
            725,
            720,
            715,
            710,
            705,
            700,
            695,
            690,
            685,
            680,
            675,
            670,
            665,
            660,
            655,
            650,
            645,
            640,
            635,
            630,
            625,
            620,
            615,
            610,
            605,
            600,
            595,
            590,
            585,
            580,
            575,
            570,
            565,
            560,
            555,
            550,
            545,
            540,
            535,
            530,
            525,
            520,
            515,
            510,
            505,
            500,
            495,
            490,
            485,
            480,
            475,
            470,
            465,
            460,
            455,
            450,
            445,
            440,
            435,
            430,
            425,
            420,
            415,
            410,
            405,
            400,
        ],
    },
    "4.34": {
        "name": "Minimal Approach to Control the pH",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 100,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "4.37": {
        "name": "Start Delay",
        "device_class": None,
        "state_class": None,
        "coefficient": 1,
        "unit_of_measurement": "min",
        "entity_type": "select",
        "options": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44,
            45,
            46,
            47,
            48,
            49,
            50,
            51,
            52,
            53,
            54,
            55,
            56,
            57,
            58,
            59,
            60,
        ],
    },
    "4.38": {
        "name": "pH Dosing Cycle",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": "s",
        "entity_type": "sensor",
    },
    "4.47": {
        "name": "pH Dosing Speed",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": "%",
        "entity_type": "sensor",
    },
    "4.67": {
        "name": "SW Version",
        "device_class": None,
        "state_class": None,  # Firmware version is not a measurement
        "coefficient": 100,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "4.68": {
        "name": "SW Date",
        "device_class": None,
        "state_class": None,
        "coefficient": -1,  # Treat result as string
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "4.69": {
        "name": "Hourly Counter / Reset every 24h",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": "h",
        "entity_type": "sensor",
    },
    "4.82": {
        "name": "Redox",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": "mV",
        "entity_type": "sensor",
    },
    "4.89": {
        "name": "pH Dosing Rate",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": "%",
        "entity_type": "sensor",
    },
    "4.98": {
        "name": "Temperature",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 10,
        "unit_of_measurement": "°C",
        "entity_type": "sensor",
    },
    "4.102": {
        "name": "Conductivity",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 10,
        "unit_of_measurement": "mS/cm",
        "entity_type": "sensor",
    },
    "4.107": {
        "name": "Battery Voltage",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 100,
        "unit_of_measurement": "V",
        "entity_type": "sensor",
    },
    "4.182": {
        "name": "pH",
        "device_class": SensorDeviceClass.PH,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 10,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.3": {
        "name": "pH Production Rate",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "select",
        "options": [
            "19.3",  # 0.25x
            "19.4",  # 0.5x
            "19.5",  # 0.75x
            "19.6",  # 1.0x
            "19.7",  # 1.25x
            "19.8",  # 1.5x
            "19.9",  # 2x
            "19.10",  # 3x
            "19.11",  # 5x
            "19.12",  # 10x
        ],
    },
    "5.29": {
        "name": "Flow Pump Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.37": {
        "name": "Gas Sensor",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.80": {
        "name": "pH Minus Canister Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.83": {
        "name": "Cover",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.184": {
        "name": "Filtration mode",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "select",
        "options": [
            "19.315",  # Low
            "19.316",  # Med
            "19.317",  # High
            "19.346",  # Auto
            "19.330",  # Smart
            "19.338",  # Frost
            "19.312",  # Off
        ],
    },
    "5.186": {
        "name": "Out 1 Mode",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "select",
        "options": [
            "19.311",  # Out On
            "19.100",  # Out Off
            "19.345",  # Out Auto
        ],
    },
    "5.187": {
        "name": "Out 2 Mode",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "select",
        "options": [
            "19.311",  # Out On
            "19.100",  # Out Off
            "19.345",  # Out Auto
        ],
    },
    "5.188": {
        "name": "Out 3 Mode",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "select",
        "options": [
            "19.311",  # Out On
            "19.100",  # Out Off
            "19.345",  # Out Auto
        ],
    },
    "5.189": {
        "name": "Out 4 Mode",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "select",
        "options": [
            "19.311",  # Out On
            "19.100",  # Out Off
            "19.345",  # Out Auto
        ],
    },
}

# Additional sensor types for Automatic SALT
SENSOR_TYPES_AUTOMATIC_SALT = {
    **SENSOR_TYPES_AUTOMATIC,  # Include all base sensors
    "4.51": {
        "name": "Polarity Reversal Times",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": "min",
        "entity_type": "sensor",
    },
    "4.66": {
        "name": "Minimum Redox Produktion",
        "device_class": None,
        "state_class": None,
        "coefficient": 1,
        "unit_of_measurement": "%",
        "entity_type": "select",
        "options": [
            100,
            95,
            90,
            85,
            80,
            75,
            70,
            65,
            60,
            55,
            50,
            45,
            40,
            35,
            30,
            25,
            20,
            15,
        ],
    },
    "4.91": {
        "name": "Electrolyzer Production Rate",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": "%",
        "entity_type": "sensor",
    },
    "4.100": {
        "name": "Salt",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 10,
        "unit_of_measurement": "g/l",
        "entity_type": "sensor",
    },
    "4.104": {
        "name": "Electrolyzer Voltage",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 10,
        "unit_of_measurement": "V",
        "entity_type": "sensor",
    },
    "4.105": {
        "name": "Electrolyzer Current",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 10,
        "unit_of_measurement": "A",
        "entity_type": "sensor",
    },
    "4.112": {
        "name": "Time Before Next Polarity Reversal",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": "s",
        "entity_type": "sensor",
    },
    "4.119": {
        "name": "Time Since Polarity Reversal",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": "s",
        "entity_type": "sensor",
    },
    "4.144": {
        "name": "Salt Preferred Level",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 10,
        "unit_of_measurement": "g/l",
        "entity_type": "select",
        "options": [
            1.0,
            1.1,
            1.2,
            1.3,
            1.4,
            1.5,
            1.6,
            1.7,
            1.8,
            1.9,
            2.0,
            2.1,
            2.2,
            2.3,
            2.4,
            2.5,
            2.6,
            2.7,
            2.8,
            2.9,
            3.0,
            3.1,
            3.2,
            3.3,
            3.4,
            3.5,
            3.6,
            3.7,
            3.8,
            3.9,
            4.0,
            4.1,
            4.2,
            4.3,
            4.4,
            4.5,
            4.6,
            4.7,
            4.8,
            4.9,
            5.0,
        ],
    },
    "5.40": {
        "name": "Salt electrolysis ON/OFF",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "select",
        "options": [
            "19.17",  # Yes
            "19.18",  # No
        ],
    },
    "5.41": {
        "name": "Redox Mode",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "select",
        "options": [
            "19.195",  # Auto
            "19.115",  # Auto Plus
            "19.106",  # Constant production
        ],
    },
    "5.98": {
        "name": "Flow Contact",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
}

# Additional sensor types for Automatic Cl-pH
SENSOR_TYPES_AUTOMATIC_CL_PH = {
    **SENSOR_TYPES_AUTOMATIC,  # Include all base sensors
    "4.90": {
        "name": "Cl Dosing Rate",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": "%",
        "entity_type": "sensor",
    },
    "5.28": {
        "name": "Flow In Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.175": {
        "name": "Cl Adjust Dosing Amount",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": "%",
        "entity_type": "select",
        "options": [
            "19.3",  # 0.25x
            "19.4",  # 0.5x
            "19.5",  # 0.75x
            "19.6",  # 1.0x
            "19.7",  # 1.25x
            "19.8",  # 1.5x
            "19.9",  # 2x
            "19.10",  # 3x
            "19.11",  # 5x
            "19.12",  # 10x
        ],
    },
    "5.169": {
        "name": "Cl Canister Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
}

# Sensor types for PM5 Chlorine
SENSOR_TYPES_PM5_CHLORINE = {
    "4.3001": {
        "name": "pH Target",
        "device_class": SensorDeviceClass.PH,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 100,
        "unit_of_measurement": None,
        "entity_type": "select",
        "options": [
            6.2,
            6.3,
            6.4,
            6.5,
            6.6,
            6.7,
            6.8,
            6.9,
            7.0,
            7.1,
            7.2,
            7.3,
            7.4,
            7.5,
            7.6,
            7.7,
            7.8,
            7.9,
            8.0,
            8.1,
            8.2,
        ],
    },
    "4.3002": {
        "name": "pH Alert Min",
        "device_class": SensorDeviceClass.PH,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 100,
        "unit_of_measurement": None,
        "entity_type": "select",
        "options": [
            5.7,
            5.8,
            5.9,
            6.0,
            6.1,
            6.2,
            6.3,
            6.4,
            6.5,
            6.6,
            6.7,
            6.8,
            6.9,
            7.0,
            7.1,
            7.2,
        ],
    },
    "4.3003": {
        "name": "pH Alert Max",
        "device_class": SensorDeviceClass.PH,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 100,
        "unit_of_measurement": None,
        "entity_type": "select",
        "options": [
            7.2,
            7.3,
            7.4,
            7.5,
            7.6,
            7.7,
            7.8,
            7.9,
            8.0,
            8.1,
            8.2,
            8.3,
            8.4,
            8.5,
            8.6,
            8.7,
        ],
    },
    "4.3017": {
        "name": "Setpoint Chlorine",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 100,
        "unit_of_measurement": "mg/l",
        "entity_type": "select",
        "options": [
            0.1,
            0.2,
            0.3,
            0.4,
            0.5,
            0.6,
            0.7,
            0.8,
            0.9,
            1.0,
            1.1,
            1.2,
            1.3,
            1.4,
            1.5,
            1.6,
            1.7,
            1.8,
            1.9,
            2.0,
        ],
    },
    "4.3018": {
        "name": "Lower Alarm threshold Chlorine",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 100,
        "unit_of_measurement": "mg/l",
        "entity_type": "select",
        "options": [
            0.1,
            0.2,
            0.3,
            0.4,
            0.5,
            0.6,
            0.7,
            0.8,
            0.9,
            1.0,
            1.1,
            1.2,
            1.3,
            1.4,
            1.5,
        ],
    },
    "4.3019": {
        "name": "Upper Alarm threshold Chlorine",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 100,
        "unit_of_measurement": "mg/l",
        "entity_type": "select",
        "options": [
            0.4,
            0.5,
            0.6,
            0.7,
            0.8,
            0.9,
            1.0,
            1.1,
            1.2,
            1.3,
            1.4,
            1.5,
            1.6,
            1.7,
            1.8,
            1.9,
            2.0,
            2.1,
            2.2,
            2.3,
            2.4,
            2.5,
            2.6,
            2.7,
            2.8,
            2.9,
            3.0,
        ],
    },
    "4.3049": {
        "name": "Setpoint Redox",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": "mV",
        "entity_type": "select",
        "options": [
            950,
            945,
            940,
            935,
            930,
            925,
            920,
            915,
            910,
            905,
            900,
            895,
            890,
            885,
            880,
            875,
            870,
            865,
            860,
            855,
            850,
            845,
            840,
            835,
            830,
            825,
            820,
            815,
            810,
            805,
            800,
            795,
            790,
            785,
            780,
            775,
            770,
            765,
            760,
            755,
            750,
            745,
            740,
            735,
            730,
            725,
            720,
            715,
            710,
            705,
            700,
            695,
            690,
            685,
            680,
            675,
            670,
            665,
            660,
            655,
            650,
            645,
            640,
            635,
            630,
            625,
            620,
            615,
            610,
            605,
            600,
            595,
            590,
            585,
            580,
            575,
            570,
            565,
            560,
            555,
            550,
            545,
            540,
            535,
            530,
            525,
            520,
            515,
            510,
            505,
            500,
            495,
            490,
            485,
            480,
            475,
            470,
            465,
            460,
            455,
            450,
            445,
            440,
            435,
            430,
            425,
            420,
            415,
            410,
            405,
            400,
        ],
    },
    "4.3051": {
        "name": "Redox Alert Min",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": "mV",
        "entity_type": "select",
        "options": [
            850,
            845,
            840,
            835,
            830,
            825,
            820,
            815,
            810,
            805,
            800,
            795,
            790,
            785,
            780,
            775,
            770,
            765,
            760,
            755,
            750,
            745,
            740,
            735,
            730,
            725,
            720,
            715,
            710,
            705,
            700,
            695,
            690,
            685,
            680,
            675,
            670,
            665,
            660,
            655,
            650,
            645,
            640,
            635,
            630,
            625,
            620,
            615,
            610,
            605,
            600,
            595,
            590,
            585,
            580,
            575,
            570,
            565,
            560,
            555,
            550,
            545,
            540,
            535,
            530,
            525,
            520,
            515,
            510,
            505,
            500,
            495,
            490,
            485,
            480,
            475,
            470,
            465,
            460,
            455,
            450,
            445,
            440,
            435,
            430,
            425,
            420,
            415,
            410,
            405,
            400,
            395,
            390,
            385,
            380,
            375,
            370,
            365,
            360,
            355,
            350,
            345,
            340,
            335,
            330,
            325,
            320,
            315,
            310,
            305,
            300,
            295,
            290,
            285,
            280,
            275,
            270,
            265,
            260,
            255,
            250,
            245,
            240,
            235,
            230,
            225,
            220,
            215,
            210,
            205,
            200,
        ],
    },
    "4.3053": {
        "name": "Redox Alert Max",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": "mV",
        "entity_type": "select",
        "options": [
            995,
            990,
            985,
            980,
            975,
            970,
            965,
            960,
            955,
            950,
            945,
            940,
            935,
            930,
            925,
            920,
            915,
            910,
            905,
            900,
            895,
            890,
            885,
            880,
            875,
            870,
            865,
            860,
            855,
            850,
            845,
            840,
            835,
            830,
            825,
            820,
            815,
            810,
            805,
            800,
            795,
            790,
            785,
            780,
            775,
            770,
            765,
            760,
            755,
            750,
            745,
            740,
            735,
            730,
            725,
            720,
            715,
            710,
            705,
            700,
            695,
            690,
            685,
            680,
            675,
            670,
            665,
            660,
            655,
            650,
            645,
            640,
            635,
            630,
            625,
            620,
            615,
            610,
            605,
            600,
            595,
            590,
            585,
            580,
            575,
            570,
            565,
            560,
            555,
            550,
            545,
            540,
            535,
            530,
            525,
            520,
            515,
            510,
            505,
            500,
        ],
    },
    "4.4001": {
        "name": "pH",
        "device_class": SensorDeviceClass.PH,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 100,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "4.4008": {
        "name": "Cl",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 100,
        "unit_of_measurement": "mg/l",
        "entity_type": "sensor",
    },
    "4.4022": {
        "name": "Redox",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": "mV",
        "entity_type": "sensor",
    },
    "4.4033": {
        "name": "Water Temperature",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 10,
        "unit_of_measurement": "°C",
        "entity_type": "sensor",
    },
    "4.4047": {
        "name": "Battery",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 100,
        "unit_of_measurement": "V",
        "entity_type": "sensor",
    },
    "4.4069": {
        "name": "Air Temperature",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 10,
        "unit_of_measurement": "°C",
        "entity_type": "sensor",
    },
    "4.4132": {
        "name": "Active Alarms",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "coefficient": 1,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.5427": {
        "name": "Filter Pump Mode",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "select",
        "options": [
            "7389",  # Eco
            "7390",  # Normal
            "7391",  # High
            "7392",  # Auto
            "7393",  # Off
        ],
    },
    "5.5433": {
        "name": "Out 1",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "button",
        "actions": {
            "On": "7408",
            "Off": "7407",
            "Auto": "7427",
        },
    },
    "5.5434": {
        "name": "Out 2",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "button",
        "actions": {
            "On": "7408",
            "Off": "7407",
            "Auto": "7427",
        },
    },
    "5.5435": {
        "name": "Out 3",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "button",
        "actions": {
            "On": "7408",
            "Off": "7407",
            "Auto": "7427",
        },
    },
    "5.5436": {
        "name": "Out 4",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "button",
        "actions": {
            "On": "7408",
            "Off": "7407",
            "Auto": "7427",
        },
    },
    # Out 5-10 button IDs assumed sequential (not verified).
    "5.5485": {
        "name": "Out 5",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "button",
        "actions": {
            "On": "7408",
            "Off": "7407",
            "Auto": "7427",
        },
    },
    "5.5519": {
        "name": "Out 6",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "button",
        "actions": {
            "On": "7408",
            "Off": "7407",
            "Auto": "7427",
        },
    },
    "5.5553": {
        "name": "Out 7",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "button",
        "actions": {
            "On": "7408",
            "Off": "7407",
            "Auto": "7427",
        },
    },
    "5.5587": {
        "name": "Out 8",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "button",
        "actions": {
            "On": "7408",
            "Off": "7407",
            "Auto": "7427",
        },
    },
    "5.5621": {
        "name": "Out 9",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "button",
        "actions": {
            "On": "7408",
            "Off": "7407",
            "Auto": "7427",
        },
    },
    "5.5655v": {
        "name": "Out 10",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "button",
        "actions": {
            "On": "7408",
            "Off": "7407",
            "Auto": "7427",
        },
    },
    # Availability sensors for the Out 1-10 buttons.
    # Values: 7003 = Yes (available), 7004 = No (unavailable).
    # Out 1 ID (5.6104) confirmed; Out 2-10 IDs assumed sequential.
    "5.6104": {
        "name": "Out 1 Available",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6105": {
        "name": "Out 2 Available",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6106": {
        "name": "Out 3 Available",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6107": {
        "name": "Out 4 Available",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6108": {
        "name": "Out 5 Available",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6109": {
        "name": "Out 6 Available",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6110": {
        "name": "Out 7 Available",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6111": {
        "name": "Out 8 Available",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6112": {
        "name": "Out 9 Available",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6113": {
        "name": "Out 10 Available",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6012": {
        "name": "pH Pump Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6013": {
        "name": "Cl Pump Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6015": {
        "name": "Redox Pump Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6064": {
        "name": "pH Canister Level",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6065": {
        "name": "pH Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6066": {
        "name": "Cl Canister Level",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6069": {
        "name": "Redox Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    # On/off status sensors for the Out 1-10 buttons.
    # Values: 7001 = On, 7002 = Off.
    # Out 1 ID (5.6028) confirmed; Out 2-10 IDs assumed sequential.
    "5.6028": {
        "name": "Out 1 Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6029": {
        "name": "Out 2 Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6030": {
        "name": "Out 3 Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6031": {
        "name": "Out 4 Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6058": {
        "name": "Out 5 Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6059": {
        "name": "Out 6 Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6060": {
        "name": "Out 7 Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6061": {
        "name": "Out 8 Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6062": {
        "name": "Out 9 Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6063": {
        "name": "Out 10 Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6039": {
        "name": "Heating Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    # System status sensors — values: 7524 (Ok) / 7526 (Warning)
    "5.6067": {
        "name": "pH System Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6071": {
        "name": "Cl System Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
    "5.6072": {
        "name": "Redox System Status",
        "device_class": None,
        "state_class": None,
        "coefficient": None,
        "unit_of_measurement": None,
        "entity_type": "sensor",
    },
}
